version: '3'

services:
  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_db
    ports:
      - '5432:5432'
    volumes:
      - ./sql/db:/var/lib/postgresql/data